### ISSUE TITLE
> is missing for Live Clock on launcher

### ISSUE THREAD

**Issue by gonicdroid** [el0xren/Samsung_Additional_Features#2]
<SEC_FLOATING_FEATURE_LAUNCHER_SUPPORT_CLOCK_LIVE_ICON>TRUE</SEC_FLOATING_FEATURE_LAUNCHER_SUPPORT_CLOCK_LIVE_ICO

**Comment by el0xren** [comment]
Which OneUi version?

**Comment by gonicdroid** [comment]
Nono, i refer to the last ">" in the line, you dont closed the xml string on your readme.md

**Comment by el0xren** [comment]
> Nono, i refer to the last ">" in the line, you dont closed the xml string on your readme.md

ooof, thanks😂😂
